id = "leflon-theme"
name = "Leflon Theme"
version = "1.0.0"
schema_version = 1
authors = ["Paul Leflon"]
description = "Vibrant theme for joyful programming."
repository = "https://github.com/leflon/zed-customization"
